name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-lint:
    name: Run Tests and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Run flake8 linter
        run: docker-compose run --rm app sh -c "flake8"
